# Generated by Django 5.1.3 on 2024-11-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=250)),
                ('isbn', models.CharField(max_length=13)),
                ('pengarang', models.CharField(max_length=250)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('tanggal_rilis', models.DateField()),
                ('jumlah_halaman', models.IntegerField()),
                ('gambar', models.ImageField(upload_to='book/images/')),
            ],
        ),
    ]
